name: esp8266-bb-mini

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-20.04
    container: domi3006/docker-kicad-ci:latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: Run preflight checks (ERC, DRC)
      run: |
        kiplot -d Output preflight 

  generate_artifacts:
    runs-on: ubuntu-20.04
    container: domi3006/docker-kicad-ci:latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: Produce outputs (pdf layout and schematic, pngs and models of the board)
      run: |
        kiplot -d Output -s run_erc,run_drc pdf_pcb_print pcbdraw_bot pcbdraw_top step dxf
    - name: Retrieve results
      uses: actions/upload-artifact@v1
      with:
        name: Artifacts
        path: Output
